#!/usr/bin/env python3
"""
Align on_screen_text entries to narration timing using anchor keywords.

After TTS audio generation produces captions with timestamps, this script
matches each scene's on_screen_text_anchors against the captions to compute
precise appear_at_ms values. This creates narration-synced staggered reveal
animations where visual elements enter the screen at the exact moment the
narrator speaks the corresponding phrase.

Usage:
    python align_anchors.py <storyboard.normalized.json> <captions.json>

The storyboard is updated in place. Each scene's on_screen_text is converted
from string[] to OnScreenTextItem[] with appear_at_ms values.

Requires:
    - on_screen_text_anchors in each scene (generated by article-to-storyboard
      or manually added)
    - captions.json produced by generate_audio.py

If a scene has no anchors, on_screen_text is left unchanged.
If an anchor keyword is not found in captions, a fallback equal-spacing
strategy distributes elements across the scene duration.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any


def load_json(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def dump_json(path: str, value: dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(value, f, ensure_ascii=False, indent=2)
        f.write("\n")


def group_captions_by_scene(captions: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for cap in captions:
        sid = cap.get("scene_id", "")
        if sid not in groups:
            groups[sid] = []
        groups[sid].append(cap)
    return groups


def find_anchor_time(
    anchor: str,
    scene_captions: list[dict[str, Any]],
    scene_start_ms: int,
) -> int | None:
    """在该 scene 的 captions 中找到包含 anchor 关键词的第一条，返回相对于 scene 起点的毫秒偏移。"""
    if not anchor:
        return None
    for cap in scene_captions:
        if anchor in cap.get("text", ""):
            return cap["start_ms"] - scene_start_ms
    return None


def compute_fallback_time(index: int, total: int, scene_duration_ms: int) -> int:
    """当 anchor 未命中时，按等间隔分配时间点。"""
    return int(scene_duration_ms * index / max(total, 1))


def ensure_monotonic(items: list[dict[str, Any]], scene_duration_ms: int, min_gap_ms: int = 2000) -> None:
    """确保 appear_at_ms 严格递增，相邻元素至少间隔 min_gap_ms。"""
    seen: dict[int, bool] = {}
    for i, item in enumerate(items):
        t = item["appear_at_ms"]
        if t in seen and i > 0:
            prev_time = items[i - 1]["appear_at_ms"]
            new_time = min(prev_time + min_gap_ms, int(scene_duration_ms * 0.9))
            item["appear_at_ms"] = new_time
        seen[t] = True

    for i in range(1, len(items)):
        if items[i]["appear_at_ms"] <= items[i - 1]["appear_at_ms"]:
            items[i]["appear_at_ms"] = items[i - 1]["appear_at_ms"] + min_gap_ms


def align_scene(
    scene: dict[str, Any],
    scene_captions: list[dict[str, Any]],
) -> tuple[int, int]:
    """对齐单个 scene 的 on_screen_text，返回 (aligned_count, fallback_count)。"""
    anchors = scene.get("on_screen_text_anchors", [])
    texts = scene.get("on_screen_text", [])
    if not anchors or not texts:
        return 0, 0

    scene_start_ms = int(scene.get("start_sec", 0) * 1000)
    scene_duration_ms = int(scene.get("duration_sec", 10) * 1000)

    aligned = 0
    fallback = 0
    new_items: list[dict[str, Any]] = []

    for i, anchor_info in enumerate(anchors):
        text = anchor_info.get("text", "") or (texts[i] if i < len(texts) else "")
        anchor = anchor_info.get("anchor", "")

        appear_at_ms = find_anchor_time(anchor, scene_captions, scene_start_ms)
        if appear_at_ms is not None:
            appear_at_ms = max(0, appear_at_ms)
            aligned += 1
        else:
            appear_at_ms = compute_fallback_time(i, len(anchors), scene_duration_ms)
            fallback += 1

        new_items.append({
            "text": text,
            "appear_at_ms": appear_at_ms,
            "anchor": anchor,
        })

    min_gap = max(2000, scene_duration_ms // (len(new_items) + 1))
    ensure_monotonic(new_items, scene_duration_ms, min_gap)

    scene["on_screen_text"] = new_items
    return aligned, fallback


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Align on_screen_text to narration timing via anchor keywords."
    )
    parser.add_argument("storyboard", help="Normalized storyboard JSON path (updated in place)")
    parser.add_argument("captions", help="Captions JSON path (from generate_audio.py)")
    args = parser.parse_args()

    if not os.path.exists(args.storyboard):
        print(f"ERROR: storyboard not found: {args.storyboard}", file=sys.stderr)
        return 1
    if not os.path.exists(args.captions):
        print(f"ERROR: captions not found: {args.captions}", file=sys.stderr)
        return 1

    storyboard = load_json(args.storyboard)
    captions_data = load_json(args.captions)
    all_captions = captions_data.get("captions", [])
    if not isinstance(all_captions, list):
        all_captions = []

    scene_captions = group_captions_by_scene(all_captions)

    total_aligned = 0
    total_fallback = 0
    scenes_processed = 0

    for scene in storyboard.get("scenes", []):
        sid = scene.get("id", "")
        caps = scene_captions.get(sid, [])
        aligned, fallback = align_scene(scene, caps)
        if aligned + fallback > 0:
            scenes_processed += 1
        total_aligned += aligned
        total_fallback += fallback

    dump_json(args.storyboard, storyboard)

    print(f"Processed {scenes_processed} scenes with anchors")
    print(f"Aligned {total_aligned} anchors from captions")
    print(f"Fallback (equal spacing) for {total_fallback} anchors")
    print(f"Updated: {args.storyboard}")

    for scene in storyboard.get("scenes", []):
        ost = scene.get("on_screen_text", [])
        if ost and isinstance(ost[0], dict):
            items = ", ".join(
                f"{o.get('anchor', '')}@{o['appear_at_ms']}ms" for o in ost
            )
            print(f"  {scene['id']}: {items}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
